### ISSUE TITLE
Bank and Consumer Coloring

### ISSUE THREAD

**Issue by madelynpetersen** [agentjwall/MAS_LendingSystem#3]
Banks will be colored either green or red based on whether
      assets>assets(defaulted) -> green
      assets<assets(defaulted) -> red 

Consumers will be colored shades of blue. As a consumer agent gets closer to its splurging threshold is will get lighter and then maybe turn purple when it splurges and asks for a loan?

**Comment by clottman** [comment]
Banker: Check out the BankerStyle class added in this commit. https://github.com/agentjwall/MAS_LendingSystem/commit/7e0c0a2ebc0084b2eb725d12976155432bdbc881
