### ISSUE TITLE
Add parameters for the new things we want to be able to control

### ISSUE THREAD

**Issue by clottman** [agentjwall/MAS_LendingSystem#34]

**Comment by madelynpetersen** [comment]
These are a lot of the things that I think we will need...
- [x] Number of banks
- [ ] size of banks
- [x] number of agents?
- [ ] number of neighborhoods?
- [ ] size of neighborhoods?
- [ ] Interconnectivity of neighborhoods. 

bank risk
- [ ]   % risk seeking
- [ ]   % risk neutral
- [ ]   % risk averse

consumer level of influenceable
- [ ]   % highly influenced
- [ ]   % moderately influenced 
- [ ]   % slightly influenced

consumer splurge probability
- [ ]   % high splurge probability
- [ ]   % moderate splurge probability
- [ ]   % low splurge probability

clustering
- [ ]   high, med. or low or no 
- [ ]   chosen variable and type
