### ISSUE TITLE
Add shared Neighborhood probability

### ISSUE THREAD

**Issue by agentjwall** [agentjwall/MAS_LendingSystem#41]

**Comment by clottman** [comment]
final List<GridCell<Bug>> bugNeighborhood = new GridCellNgh<Bug>(
                                grid, location, Bug.class,
                                Constants.BUG_REPRODUCTION_RANGE,
                                Constants.BUG_REPRODUCTION_RANGE).getNeighborhood(false);

**Comment by clottman** [comment]
Also this to get the variables:  
`final Grid<Object> grid = getGrid();`
       `final GridPoint location = grid.getLocation(this);`
